categories:
  - title: 'Novas Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Correções'
    label: 'fix'
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
version-template: 'v$MAJOR-x'
template: |
  ## Changelog para a próxima versão: $RESOLVED_VERSION
  $CHANGES
  Commits: https://github.com/lemosflavio/product-management/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
  Tag: https://github.com/lemosflavio/product-management/releases/tag/$RESOLVED_VERSION
